apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deploymentReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}-{{ .Release.Revision }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}-{{ .Release.Revision }}
    spec:
      hostname: {{ .Values.deploymentName }}-{{ .Release.Revision }}
      containers:
      - name: {{ .Values.deploymentName }}-{{ .Release.Revision }}-webviz
        image: hgtunc/boardmarker:webvizv2
        env:
        - name: WEBVIZ_PORT
          value: "31601"
        stdin: true
        tty: true		  
        ports:
        - name: webviz
          containerPort: 31601
          hostPort: 31601  
          protocol: TCP
        volumeMounts:
      - name: {{ .Values.deploymentName }}-{{ .Release.Revision }}
        image: hgtunc/boardmarker:jackalv2
        env:
        - name: VIDEO_PORT
          value: "DFP"
        - name: USER
          value: "user"
        - name: NEKO_BIND
          value: "31001"
        - name: NEKO_UDP_PORT
          value: "59001-59001"
        - name: THEIA_PORT
          value: "31501"
        - name: ROSBRIDGE_PORT
          value: "31701"
        stdin: true
        tty: true		  
        ports:
        - name: http
          containerPort: 31001
          hostPort: 31001
          protocol: TCP
        - name: webrtc
          containerPort: 31002
          hostPort: 31002  
          protocol: UDP
        - name: theia
          containerPort: 31501
          hostPort: 31501  
          protocol: TCP
        - name: rosbridge
          containerPort: 31701
          hostPort: 31701  
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cache
          name: xgl-cache-vol
        - mountPath: /etc/bootstrap.sh
          subPath: bootstrap.sh
          name: robot-bootstrap
        - mountPath: /etc/provedge/supervisord/theia_supervisord.conf
          subPath: theia_supervisord.conf
          name: robot-theia-supervisord
        - mountPath: /etc/provedge/theia_start.sh
          subPath: theia_start.sh
          name: robot-theia-start
        - mountPath: /etc/provedge/supervisord/jackal_supervisord.conf
          subPath: jackal_supervisord.conf
          name: {{ .Values.cmSupervisordName }}-{{ .Release.Revision }}
        - mountPath: /etc/provedge/jackal_start.sh
          subPath: jackal_start.sh
          name: {{ .Values.cmStartName }}-{{ .Release.Revision }}
        - mountPath: /var/www/js/app.08718670.js
          subPath: app.08718670.js
          name: robot-app-js
        - mountPath: /var/www/index.html
          subPath: index.html
          name: robot-index
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: xgl-cache-vol
        emptyDir: {}
      - name: robot-bootstrap
        configMap:
          name: robot-bootstrap
          defaultMode: 0777
      - name: robot-theia-start
        configMap:
          name: robot-theia-start
          defaultMode: 0777
      - name: robot-theia-supervisord
        configMap:
          name: robot-theia-supervisord
          defaultMode: 0777
      - name: {{ .Values.cmStartName }}-{{ .Release.Revision }}
        configMap:
          name: {{ .Values.cmStartName }}-{{ .Release.Revision }}
          defaultMode: 0777
      - name: {{ .Values.cmSupervisordName }}-{{ .Release.Revision }}
        configMap:
          name: {{ .Values.cmSupervisordName }}-{{ .Release.Revision }}
          defaultMode: 0777
      - name: robot-app-js
        configMap:
          name: robot-app-js
          defaultMode: 0777
      - name: robot-index
        configMap:
          name: robot-index
          defaultMode: 0777