apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deploymentReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      hostname: {{ .Values.deploymentName }}
      containers:
      - name: {{ .Values.deploymentName }}-webviz
        image: hgtunc/boardmarker:webvizv2
        env:
        - name: WEBVIZ_PORT
          value: "{{ .Values.webvizPort }}"
        stdin: true
        tty: true		  
        ports:
        - name: webviz
          containerPort: {{ .Values.webvizPort }}
          hostPort: {{ .Values.webvizPort }}  
          protocol: TCP
        volumeMounts:
      - name: {{ .Values.deploymentName }}
        image: hgtunc/boardmarker:jackalv2
        env:
        - name: VIDEO_PORT
          value: "DFP"
        - name: USER
          value: "user"
        - name: NEKO_BIND
          value: "{{ .Values.httpPort }}"
        - name: NEKO_UDP_PORT
          value: "{{ .Values.webrtcPort }}-{{ .Values.webrtcPort }}"
        - name: THEIA_PORT
          value: "{{ .Values.theiaPort }}"
        - name: ROSBRIDGE_PORT
          value: "{{ .Values.rosbridgePort }}"
        stdin: true
        tty: true		  
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
          hostPort: {{ .Values.httpPort }}
          protocol: TCP
        - name: webrtc
          containerPort: {{ .Values.webrtcPort }}
          hostPort: {{ .Values.webrtcPort }}  
          protocol: UDP
        - name: theia
          containerPort: {{ .Values.theiaPort }}
          hostPort: {{ .Values.theiaPort }}
          protocol: TCP
        - name: rosbridge
          containerPort: {{ .Values.rosbridgePort }}
          hostPort: {{ .Values.rosbridgePort }}
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cache
          name: xgl-cache-vol
        - mountPath: /etc/bootstrap.sh
          subPath: bootstrap.sh
          name: robot-bootstrap
        - mountPath: /etc/provedge/supervisord/theia_supervisord.conf
          subPath: theia_supervisord.conf
          name: robot-theia-supervisord
        - mountPath: /etc/provedge/theia_start.sh
          subPath: theia_start.sh
          name: robot-theia-start
        - mountPath: /etc/provedge/supervisord/jackal_supervisord.conf
          subPath: jackal_supervisord.conf
          name: {{ .Values.cmSupervisordName }}
        - mountPath: /etc/provedge/jackal_start.sh
          subPath: jackal_start.sh
          name: {{ .Values.cmStartName }}
        - mountPath: /var/www/js/app.08718670.js
          subPath: app.08718670.js
          name: robot-app-js
        - mountPath: /var/www/index.html
          subPath: index.html
          name: robot-index
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: xgl-cache-vol
        emptyDir: {}
      - name: robot-bootstrap
        configMap:
          name: robot-bootstrap
          defaultMode: 0777
      - name: robot-theia-start
        configMap:
          name: robot-theia-start
          defaultMode: 0777
      - name: robot-theia-supervisord
        configMap:
          name: robot-theia-supervisord
          defaultMode: 0777
      - name: {{ .Values.cmStartName }}
        configMap:
          name: {{ .Values.cmStartName }}
          defaultMode: 0777
      - name: {{ .Values.cmSupervisordName }}
        configMap:
          name: {{ .Values.cmSupervisordName }}
          defaultMode: 0777
      - name: robot-app-js
        configMap:
          name: robot-app-js
          defaultMode: 0777
      - name: robot-index
        configMap:
          name: robot-index
          defaultMode: 0777