apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.httpPort }}
    targetPort: {{ .Values.httpPort }}
    nodePort: {{ .Values.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.webrtcPort }}
    targetPort: {{ .Values.webrtcPort }}
    nodePort: {{ .Values.webrtcPort }}
    protocol: UDP
    name: webrtc
  - port: {{ .Values.theiaPort }}
    targetPort: {{ .Values.theiaPort }}
    nodePort: {{ .Values.theiaPort }}
    protocol: TCP
    name: theia
  - port: {{ .Values.rosbridgePort }}
    targetPort: {{ .Values.rosbridgePort }}
    nodePort: {{ .Values.rosbridgePort }}
    protocol: TCP
    name: rosbridge
  - port: {{ .Values.webvizPort }}
    targetPort: {{ .Values.webvizPort }}
    nodePort: {{ .Values.webvizPort }}
    protocol: TCP
    name: webviz

  selector:
    app: {{ .Values.deploymentName }}	  
  selector:
    app: {{ .Values.deploymentName }}	