apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 31001
    targetPort: 31001
    nodePort: 31001
    protocol: TCP
    name: http
  - port: 31501
    targetPort: 31501
    nodePort: 31501
    protocol: TCP
    name: theia
  - port: 31601
    targetPort: 31601
    nodePort: 31601
    protocol: TCP
    name: webviz
  - port: 31701
    targetPort: 31701
    nodePort: 31701
    protocol: TCP
    name: rosbridge
  - port: 31002
    targetPort: 31002
    nodePort: 31002
    protocol: UDP
    name: webrtc
  selector:
    app: {{ .Values.deploymentName }}-{{ .Release.Revision }}	  
  selector:
    app: {{ .Values.deploymentName }}-{{ .Release.Revision }}	